jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/kb7spring
jdbc.username=root
jdbc.password=1234

# JPA
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true

# OAUTH - KAKAO
kakao.rest_key=0796165ae4efcc1e9a988de70f839428
kakao.redirect_uri=http://localhost:8080/oauth/kakao/callback

