jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/kb7spring
jdbc.username=root
jdbc.password=1234

# File Upload Settings
file.location=c:/upload
file.max-file-size=-1
file.max-request-size=-1
file.file-size-threshold=5242880